version: 2
updates:
  # Enable monthly npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Limit the number of open pull requests for npm updates
    open-pull-requests-limit: 5
    # Group all minor and patch updates into a single PR
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Always create security updates immediately (overrides monthly schedule)
    allow:
      - dependency-type: "all"
    # Target branch for dependency updates
    target-branch: "main"
    # Customize commit messages
    commit-message:
      prefix: "deps"
      include: "scope"
    # Add reviewers for dependency PRs (optional - can be customized)
    reviewers:
      - "talhabilal-dev"